AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Description: 'Avoid methods longer than 15 lines of code.'
  StyleGuide: '#short-methods'
  Enabled: true
  CountComments: false
  Max: 15
