AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Description: 'Avoid methods longer than 15 lines of code.'
  StyleGuide: '#short-methods'
  Enabled: true
  CountComments: false
  Max: 15

Metrics/BlockLength:
  Description: 'Avoid long blocks with many lines.'
  Enabled: true
  CountComments: false
  Max: 25
  Exclude:
    - '**/*.gemspec'
    - '**/*_spec.rb'
