version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@3.4

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - hmpps/build_docker:
          name: build_docker
          publish: false
          persist_container_image: true

      - hmpps/trivy_pipeline_scan:
          name: trivy_scan_low_medium_cves
          fail_build: false
          cve_severities_to_check: UNKNOWN,LOW,MEDIUM
          requires:
            - build_docker

      - hmpps/trivy_pipeline_scan:
          name: trivy_scan
          requires:
            - build_docker

      - hmpps/publish_docker:
          name: publish_docker
          requires:
            - helm_lint
            - integration_test
            - trivy_scan
            - unit_test
          filters:
            branches:
              only:
                - main

      - hmpps/deploy_env:
          name: deploy_dev
          env: dev
          context: hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - publish_docker

      - request-preprod-approval:
          type: approval
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          name: deploy_preprod
          env: preprod
          context:
            - hmpps-common-vars
            - ppud-replacement-preprod
          requires:
            - request-preprod-approval

      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          env: prod
          context:
            - hmpps-common-vars
            - ppud-replacement-prod
          requires:
            - request-prod-approval
          slack_notification: true
          slack_channel_name: << pipeline.parameters.releases-slack-channel >>

  security:
    triggers:
      - schedule:
          cron: "0 7 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - check_outdated:
          context:
            - hmpps-common-vars
      - hmpps/npm_security_audit:
          context:
            - hmpps-common-vars
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
      - hmpps/veracode_policy_scan:
          context:
            - veracode-credentials
            - hmpps-common-vars
      - hmpps/trivy_latest_scan:
          context:
            - hmpps-common-vars
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
