version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@3.6
  ruby: circleci/ruby@1

parameters:
  alerts-slack-channel:
    type: string
    default: ppud-replacement-devs

jobs:
  test:
    docker:
      - image: cimg/ruby:2.7-node
    environment:
      CIRCLE_CI_AUTH_TOKEN: foobar
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop
      - run:
          name: Run Test Suite
          command: bundle exec rake test

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test

      - hmpps/helm_lint:
          name: helm_lint

      - hmpps/build_docker:
          name: build_docker
          publish: false
          persist_container_image: true
          requires:
            - test

      - hmpps/trivy_pipeline_scan:
          name: trivy_scan_low_medium_cves
          fail_build: false
          cve_severities_to_check: UNKNOWN,LOW,MEDIUM
          requires:
            - build_docker

      - hmpps/trivy_pipeline_scan:
          name: trivy_scan
          requires:
            - build_docker

      - hmpps/publish_docker:
          name: publish_docker
          requires:
            - helm_lint
            - trivy_scan
          filters:
            branches:
              only:
                - main

      - hmpps/deploy_env:
          name: deploy_dev
          env: dev
          context: hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - publish_docker

  security:
    triggers:
      - schedule:
          cron: "0 7 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/veracode_policy_scan:
          context:
            - veracode-credentials
            - hmpps-common-vars
          teams: Sentence Management
          slack_channel: << pipeline.parameters.alerts-slack-channel >>

      - hmpps/trivy_latest_scan:
          context:
            - hmpps-common-vars
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
